name: ci

on:
  # schedule:
  # - cron: '0 3 * * SUN'
  push:
    branches:
      - main
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # -
      #   name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ vars.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest


      - uses: actions/checkout@v3
  
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with: 
          python-version: 3.8
          
      - name: Install dependencies
        run: |
          make install
          
      - name: Lint with pylint
        run: |
          make lint
          
      - name: Run tests with pytest
        run: |
          make test
          
      - name: Format code with black
        run: |
          make format
          
      - name: Deploy the app
        run: |
          make deploy
